import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        stage: {
          new: "hsl(var(--stage-new))",
          called: "hsl(var(--stage-called))",
          onboard: "hsl(var(--stage-onboard))",
          live: "hsl(var(--stage-live))",
          lost: "hsl(var(--stage-lost))",
          "new-bg": "hsl(var(--stage-new-bg))",
          "called-bg": "hsl(var(--stage-called-bg))",
          "onboard-bg": "hsl(var(--stage-onboard-bg))",
          "live-bg": "hsl(var(--stage-live-bg))",
          "lost-bg": "hsl(var(--stage-lost-bg))",
          purple: "hsl(var(--stage-purple))",
          teal: "hsl(var(--stage-teal))",
          indigo: "hsl(var(--stage-indigo))",
          pink: "hsl(var(--stage-pink))",
          orange: "hsl(var(--stage-orange))",
          "purple-bg": "hsl(var(--stage-purple-bg))",
          "teal-bg": "hsl(var(--stage-teal-bg))",
          "indigo-bg": "hsl(var(--stage-indigo-bg))",
          "pink-bg": "hsl(var(--stage-pink-bg))",
          "orange-bg": "hsl(var(--stage-orange-bg))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          from: { opacity: "0", transform: "translateX(100%)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.7" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    // Stage background colors
    'bg-stage-new',
    'bg-stage-called',
    'bg-stage-onboard',
    'bg-stage-live',
    'bg-stage-lost',
    'bg-stage-purple',
    'bg-stage-teal',
    'bg-stage-indigo',
    'bg-stage-pink',
    'bg-stage-orange',
    // Stage background-light colors
    'bg-stage-new-bg',
    'bg-stage-called-bg',
    'bg-stage-onboard-bg',
    'bg-stage-live-bg',
    'bg-stage-lost-bg',
    'bg-stage-purple-bg',
    'bg-stage-teal-bg',
    'bg-stage-indigo-bg',
    'bg-stage-pink-bg',
    'bg-stage-orange-bg',
    // Stage text colors
    'text-stage-new',
    'text-stage-called',
    'text-stage-onboard',
    'text-stage-live',
    'text-stage-lost',
    'text-stage-purple',
    'text-stage-teal',
    'text-stage-indigo',
    'text-stage-pink',
    'text-stage-orange',
    // Stage border colors with opacity
    'border-stage-new/30',
    'border-stage-called/30',
    'border-stage-onboard/30',
    'border-stage-live/30',
    'border-stage-lost/30',
    'border-stage-purple/30',
    'border-stage-teal/30',
    'border-stage-indigo/30',
    'border-stage-pink/30',
    'border-stage-orange/30',
  ],
} satisfies Config;
